class ConsumablesData {
  List<Map<String, dynamic>> data = [
    {
      "id": 1,
      "category": ["oil"],
      "name": "MCT Oil",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "mL",
      "servingSizeMeasurement": 15.0,
      "calories": 135.0,
      "fat": 14.0,
      "fatMeasurement": "g",
      "protein": 0.0,
      "proteinMeasurement": "",
      "carbs": 0.0,
      "carbsMeasurement": "",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": true
    },
    {
      "id": 2,
      "category": ["dairy"],
      "name": "Grass Fed Butter",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 14.0,
      "calories": 100.0,
      "fat": 11.0,
      "fatMeasurement": "g",
      "protein": 0.0,
      "proteinMeasurement": "",
      "carbs": 0.0,
      "carbsMeasurement": "",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": true
    },
    {
      "id": 3,
      "category": ["dairy", "coffee"],
      "name": "Lucerne Heavy Whipping Cream",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "ml",
      "servingSizeMeasurement": 15.0,
      "calories": 50,
      "fat": 5.0,
      "fatMeasurement": "g",
      "protein": 0.0,
      "proteinMeasurement": "",
      "carbs": 1.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 4,
      "category": ["coffee", "sweet"],
      "name": "Laird Hamilton Superfood Creamer",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 6.0,
      "calories": 40.0,
      "fat": 3.5,
      "fatMeasurement": "g",
      "protein": 0.0,
      "proteinMeasurement": "",
      "carbs": 2.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 5,
      "category": ["protein", "egg"],
      "name": "Egg",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Egg",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 6.0,
      "calories": 70.0,
      "fat": 5.0,
      "fatMeasurement": "g",
      "protein": 6.0,
      "proteinMeasurement": "",
      "carbs": 0.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 6,
      "category": ["meat", "breakfast"],
      "name": "Bacon",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Slice (including fat)",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 6.0,
      "calories": 70,
      "fat": 5.0,
      "fatMeasurement": "g",
      "protein": 6.0,
      "proteinMeasurement": "",
      "carbs": 0.0,
      "carbsMeasurement": "",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 7,
      "category": ["meat", "breakfast"],
      "name": "Turkey Sausage",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "link",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 6.0,
      "calories": 60,
      "fat": 4.0,
      "fatMeasurement": "g",
      "protein": 5.0,
      "proteinMeasurement": "g",
      "carbs": 0.5,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 8,
      "category": ["meat"],
      "name": "Natural Choice Ham",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Slice",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 6.0,
      "calories": 15,
      "fat": 0.37,
      "fatMeasurement": "g",
      "protein": 2.5,
      "proteinMeasurement": "g",
      "carbs": 0.25,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 9,
      "category": ["dairy", "sweet"],
      "name": "Two Good Coconut Yogurt",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Container",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 150.0,
      "calories": 80,
      "fat": 2.0,
      "fatMeasurement": "g",
      "protein": 12.0,
      "proteinMeasurement": "g",
      "carbs": 3.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 10,
      "category": ["oil"],
      "name": "365 Extra Virgine Olive Oil",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "mL",
      "servingSizeMeasurement": 15.0,
      "calories": 130,
      "fat": 14.0,
      "fatMeasurement": "g",
      "protein": 0.0,
      "proteinMeasurement": "",
      "carbs": 0.0,
      "carbsMeasurement": "",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 11,
      "category": ["oil"],
      "name": "Avacado Oil",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "mL",
      "servingSizeMeasurement": 15.0,
      "calories": 120,
      "fat": 14.0,
      "fatMeasurement": "g",
      "protein": 0.0,
      "proteinMeasurement": "",
      "carbs": 0.0,
      "carbsMeasurement": "",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 12,
      "category": ["nut"],
      "name": "Almond",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "per",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 1.3,
      "calories": 7.7,
      "fat": 0.7,
      "fatMeasurement": "g",
      "protein": 0.3,
      "proteinMeasurement": "g",
      "carbs": 0.2,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 13,
      "category": ["nut"],
      "name": "Cashew",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "per",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 1.6,
      "calories": 9.0,
      "fat": 0.7,
      "fatMeasurement": "g",
      "protein": 0.2,
      "proteinMeasurement": "g",
      "carbs": 0.4,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 14,
      "category": ["nut"],
      "name": "Pecan",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "per",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 1.5,
      "calories": 10.0,
      "fat": 1.1,
      "fatMeasurement": "g",
      "protein": 0.1,
      "proteinMeasurement": "g",
      "carbs": 0.1,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 15,
      "category": ["nut"],
      "name": "Walnut",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "per",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 2.0,
      "calories": 13.0,
      "fat": 1.3,
      "fatMeasurement": "g",
      "protein": 0.3,
      "proteinMeasurement": "g",
      "carbs": 0.2,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 16,
      "category": ["nut-milk"],
      "name": "Open Nature Almond Milk with Coconut",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Cup",
      "servingSizeMeasurementName": "mL",
      "servingSizeMeasurement": 240,
      "calories": 40.0,
      "fat": 2.5,
      "fatMeasurement": "g",
      "protein": 1.0,
      "proteinMeasurement": "g",
      "carbs": 2.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 17,
      "category": ["dairy"],
      "name": "White Cheddar Cheese",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Cup",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 28.0,
      "calories": 110.0,
      "fat": 9.0,
      "fatMeasurement": "g",
      "protein": 7.0,
      "proteinMeasurement": "g",
      "carbs": 0.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 18,
      "category": ["fish"],
      "name": "Fresh Salmon",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "oz",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 28.3,
      "calories": 59.0,
      "fat": 3.6,
      "fatMeasurement": "g",
      "protein": 5.6,
      "proteinMeasurement": "g",
      "carbs": 0.2,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 19,
      "category": ["fish"],
      "name": "Wild Planet Sardines",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "container",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 85.0,
      "calories": 170.0,
      "fat": 11.0,
      "fatMeasurement": "g",
      "protein": 18.0,
      "proteinMeasurement": "g",
      "carbs": 0.2,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": true
    },
    {
      "id": 19,
      "category": ["sweet"],
      "name": "Sweet Syrup",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 30.0,
      "calories": 50.0,
      "fat": 0,
      "fatMeasurement": "",
      "protein": 0,
      "proteinMeasurement": "",
      "carbs": 0,
      "carbsMeasurement": "",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 20,
      "category": ["nut"],
      "name": "Skippy Natrual Peanut Butter",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 16.0,
      "calories": 100.0,
      "fat": 8.5,
      "fatMeasurement": "g",
      "protein": 3.5,
      "proteinMeasurement": "g",
      "carbs": 4.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 21,
      "category": ["nut"],
      "name": "Almond Butter",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 16.0,
      "calories": 95.0,
      "fat": 8.5,
      "fatMeasurement": "g",
      "protein": 3.5,
      "proteinMeasurement": "g",
      "carbs": 2.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 22,
      "category": ["seed"],
      "name": "Sunflower Seeds ( shelled )",
      "servingSize": 0.25,
      "servingSizeString": "1/4",
      "servingSizeName": "Cup",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 30.0,
      "calories": 190.0,
      "fat": 15.0,
      "fatMeasurement": "g",
      "protein": 8.0,
      "proteinMeasurement": "g",
      "carbs": 3.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 23,
      "category": ["dairy"],
      "name": "Lucerne Cream Cheese",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "Tbsp",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 14.0,
      "calories": 45.0,
      "fat": 4.5,
      "fatMeasurement": "g",
      "protein": 1.0,
      "proteinMeasurement": "g",
      "carbs": 1.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 24,
      "category": ["meat"],
      "name": "Grass Fed Beef",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "oz",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 33.0,
      "calories": 57.5,
      "fat": 4.25,
      "fatMeasurement": "g",
      "protein": 5.25,
      "proteinMeasurement": "g",
      "carbs": 0.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
    {
      "id": 25,
      "category": ["vegetables"],
      "name": "Spinach",
      "servingSize": 1.0,
      "servingSizeString": "1",
      "servingSizeName": "g",
      "servingSizeMeasurementName": "g",
      "servingSizeMeasurement": 85.0,
      "calories": 20.0,
      "fat": 0.0,
      "fatMeasurement": "g",
      "protein": 2.00,
      "proteinMeasurement": "g",
      "carbs": 0.0,
      "carbsMeasurement": "g",
      "quantity": 1.0,
      "isExpanded": false,
      "showQuickAdd": false
    },
  ];

  getBuiltList() {}

  getMutableList() {}
}
